

# Name of your site (displayed in the header)
name: "HI HERI" 

# Name of the author
author: "NARNIA"

# Short bio or description (displayed in the header)
description: "I decided to dabble into your world of github wizardry! I appreciate the gansito and the orange you gave me. But most importantly appreciate your friendship and hoe smart you are"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "https://www.disneyclips.com/images/images/stitch-frog.png"


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

